name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "15 14 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Test 32 bit
      run: |
        zig build test -Dtarget=i386-linux-musl --prefix tmp
        zig build test -Dtarget=i386-linux-musl --prefix tmp -fno-stage1

    - name: Test 64 bit
      run: |
        zig build -Dtarget=x86_64-linux-musl
        zig build -Dtarget=x86_64-linux-musl -fno-stage1
